### ISSUE TITLE
[Demo] CKIP CoreNLP - Internal Server Error with WSD

### ISSUE THREAD

**Issue by emfomy** [ckiplab/issue#2]
**Describe the bug**
The system throws 500 error with WSD

**To Reproduce**
Submit with WSD only

**Expected behavior**
No error

**Screenshots**
<img width="1124" alt="Screen Shot 2021-05-13 at 11 12 36 AM" src="https://user-images.githubusercontent.com/11171959/118072315-20d5ed80-b3dc-11eb-97f9-68d911748608.png">

**Comment by victoriawu9218** [comment]
This bug is fixed.

<img width="1113" alt="螢幕快照 2021-06-01 上午2 15 25" src="https://user-images.githubusercontent.com/62533388/120229261-548b9100-c27f-11eb-9059-0777263c282b.png">
