### ISSUE TITLE
[Other] 中文詞彙向量無法下載

### ISSUE THREAD

**Issue by ShiShanLiu** [ckiplab/issue#7]
您好，遇到問題為無法於http://ckipsvr.iis.sinica.edu.tw/cemb/reg.php 與 http://ckipsvr.iis.sinica.edu.tw/cembeval/reg.php 下載中文詞彙向量，想請問可以如何成功下載到?

**Comment by ZenonLiao** [comment]
fixed

**Comment by ShiShanLiu** [comment]
Thanks!
